"""empty message

Revision ID: 29b380c57163
Revises: 
Create Date: 2020-06-18 18:23:40.528255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b380c57163'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_user', sa.Column('read', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('msg_type', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'msg_type')
    op.drop_column('conversation_user', 'read')
    # ### end Alembic commands ###
