"""empty message

Revision ID: 860db6eeb154
Revises: c14e3fd0f958
Create Date: 2020-06-03 04:47:15.146883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860db6eeb154'
down_revision = 'c14e3fd0f958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_assignment', sa.Column('filename', sa.String(length=20), nullable=True))
    op.drop_column('user_assignment', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_assignment', sa.Column('url', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('user_assignment', 'filename')
    # ### end Alembic commands ###
