"""empty message

Revision ID: a053b0fd5698
Revises: 860db6eeb154
Create Date: 2020-06-06 01:13:26.063189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a053b0fd5698'
down_revision = '860db6eeb154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'confirmed')
    # ### end Alembic commands ###
